version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "40718:40718"
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
